name 'syndicate-windows'
maintainer 'James Nduka'
maintainer_email 'james.s.nduka@synwin.co.uk'
license 'all_rights'
description 'Everything to get a Windows machine configured'
issues_url 'https://github.com/james-s-nduka/syndicate-windows/issues'
source_url 'https://github.com/james-s-nduka/syndicate-windows'
chef_version '>= 12.5'
version '1.0.0'
supports 'windows'

depends 'chef-client'
depends 'windows'
